### ISSUE TITLE
form.serialize() includes Placeholder

### ISSUE THREAD

**Issue by Uepsilon** [mathiasbynens/jquery-placeholder#197]
When gathering data via jQuery serialize() the placeholder is included in the returned string.

jQuery = 1.7.1
placeholder = 2.0.7

**Comment by amerikan** [comment]
The problem is that this plugin uses invisible input fields which I'm sure serialize assumes as a input field since it is. This will be impossible to fix, unless the plugin is rewritten to not use invisible input fields. You can use my placeholder plugin which solves same problem as this plugin, but takes a different approach which does not involve invisible input types. https://github.com/amerikan/placeholder-polyfill
