### ISSUE TITLE
ie7 input type password can not use

### ISSUE THREAD

**Issue by noinlijin** [mathiasbynens/jquery-placeholder#260]
ie10
![image](https://cloud.githubusercontent.com/assets/3073370/8051859/f0dc8c48-0eb3-11e5-8daa-abb7a5da645a.png)

----
ie7
![image](https://cloud.githubusercontent.com/assets/3073370/8051867/0261e7ce-0eb4-11e5-89fc-618b1e5e8c7e.png)

can you fiex this bug?

**Comment by Alex1990** [comment]
I have push a pull request #259 which fixes this error. In China, nearly 5% of the people use IE compatible mode (IE 7). And, it's easy to fix it. Use `prop` instead of `attr` method in [this line](https://github.com/Alex1990/jquery-placeholder/blob/7bfe3379f9b1a4149320542ad7628f0107b541dc/jquery.placeholder.js#L192)

@noinlijin You can see my repository [https://github.com/Alex1990/jquery-placeholder](https://github.com/Alex1990/jquery-placeholder) which fixed other errors. Then, download the source file (**unminified**). Hope to help you.

**Comment by amerikan** [comment]
@Alex1990 I saw your PR (haven't had a chance to test it). Can you create a new one that solely fixes this issue?

**Comment by amerikan** [comment]
@noinlijin I have merged @Alex1990 PR. Can you check out the latest version of the plugin (v2.1.2) and test to see if your issue is solved? Please do report back. Thanks.

**Comment by noinlijin** [comment]
thanks
