### ISSUE TITLE
Is this project still under maintenance

### ISSUE THREAD

**Issue by sunny-shu** [mathiasbynens/jquery-placeholder#307]
Is this project still under maintenance？I see many questions from the community did not respond
if yes,I am happy to maintain the community

**Comment by amerikan** [comment]
@sunny-shu Due to the fact that in the current age the placeholder attribute now enjoys universal native support in modern browsers, it has somewhat become obsolete. Of course there are far edge cases where old browsers like old IE versions are needed, but that market is minuscule.

With that said, it's not necessarily dead, but not active either. I have certain limited permissions to the repo, but do not own it.

What setup do you have to test in old IE versions?

**Comment by sunny-shu** [comment]
ok, i will close this issue.I just want to do something on github  to improve my skills.
